spring:
  application:
    name: product-service
  config:
    import:
    - optional:configserver:http://root:secret@localhost:8081
  boot:
    admin:
      client:
        url: http://localhost:8086
        